### PR TITLE
[4346][ADD] mrp_mto_analytic, purchase_mto_analytic

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
[4346](https://www.quartile.co/web#id=4346&menu_id=505&cids=3&action=1457&model=project.task&view_type=form)

### CODE REVIEW

**Review by yostashiro — APPROVED** [review]
@AungKoKoLin1997 Can you please update the OCA PR with the content of my commit?

**Comment by yostashiro** [comment]
@AungKoKoLin1997 Can you please add a consideration in purchase_mto_analytic to split the procurement based on the analytic distribution?  I suppose we should extend this https://github.com/OCA/OCB/blob/52bec03/addons/purchase_stock/models/stock_rule.py#L182-L191 to add analytic_distribution as a key.

Haven't checked whether an equivalent consideration is needed in mrp_mto_analytic. I am guessing not. Please help check.

**Comment by AungKoKoLin1997** [comment]
> I suppose we should extend this https://github.com/OCA/OCB/blob/52bec03/addons/purchase_stock/models/stock_rule.py#L182-L191 to add analytic_distribution as a key.

I think we can't do like this because `analytic_distribution` is json type value and we can't use as a key for `groupby`. Even we get `analytic accounts` from `analytic_distribution` and use as a key, I don't think we can get our expected behavior.

**Comment by AungKoKoLin1997** [comment]
There is blocking issue when we want to split purchase order line depends on `analytic_distribution` because of the behavior of this function. This function always return the first PO line of matched PO lines.
https://github.com/odoo/odoo/blob/990aae55b1a2b95765a848b6fc122bb69f768ce1/addons/purchase_stock/models/purchase.py#L620
It returns the first PO line.
So, in case of scenario like below, the workflow is not correct.

This is after create two PO lines depends on analytic_distribution.
Screenshot 2024-03-19 at 11 50 40

After that, when we create new document with the same analytic_distribution of existing second PO line, it checks whether it is create new PO line or use existing one. Then, it creates new PO line because the first line of existing PO doesn't have the same analytic_distribution with the coming PO line. So, we need to complete override above function.
Screenshot 2024-03-19 at 11 51 07

**Pull request merged**
