### PR TITLE
[3715][ADD] sale_tier_validation_block_print

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
[3715](https://www.quartile.co/web#id=3715&menu_id=505&cids=3&action=1457&model=project.task&view_type=form)

### CODE REVIEW

**Comment by yostashiro** [comment]
@AungKoKoLin1997 Please go ahead and create a PR in oca/sale-workflow.

**Review by kanda999 — APPROVED** [review]
Functional review

**Comment by AungKoKoLin1997** [comment]
The feature of this PR is added in https://github.com/qrtl/axls-oca/pull/151. Closing this PR.

**Comment by AungKoKoLin1997** [comment]
Closing this PR.

**Pull request closed without merging**
