### PR TITLE
[4010][ADD] sales_team_security

### PR DESCRIPTION
**Pull request by liuhehe1995**
[4010](https://www.quartile.co/web#id=4010&menu_id=505&cids=3&action=1457&model=project.task&view_type=form)

### CODE REVIEW

**Comment by liuhehe1995** [comment]
This is a low priority task, I'll fix this failing checks later.

**Review by kanda999 — APPROVED** [review]
Functional review LGTM

**Comment by AungKoKoLin1997** [comment]
I just realized that tests from stock_picking_line_sequence are failed when we install mrp in env because of this latest update PR from odoo repo.
https://github.com/odoo/odoo/pull/144276

**Comment by yostashiro** [comment]
> I just realized that tests from stock_picking_line_sequence are failed when we install mrp in env because of this latest update PR from odoo repo. [odoo/odoo#144276](https://github.com/odoo/odoo/pull/144276)

@AungKoKoLin1997 Does it actually break the functionality of `stock_picking_line_sequence`? Please follow up to fix the issue in the OCA repo.

**Comment by AungKoKoLin1997** [comment]
I put `auditlog` module together with owner related modules in CI tests.  Now the tests failed is from `stock_picking_line_sequence`. I still don't understand the reason of getting tests failed from sales_team_security if we put it together with `auditlog`. Its only happens in PR CI and there is no error when I test in dev env with these two modules together.

**Comment by yostashiro** [comment]
Fixed the CI issue.  Two points:

1. Added `odoo-addon-stock-picking-line-sequence @ git+https://github.com/qrtl/axls-oca.git@refs/pull/120/head#subdirectory=setup/stock_picking_line_sequence` in `test-requirements.txt`.
2. Updated `.github/workflows/test.yml` to seggregate `sales_team_security` from `crm`; the test setup of `sales_team_secrity` is incompatible with `crm` which adds a required field `alias_id` to the `crm.team` model.

Before merging this PR, we need to update `test-requirements.txt` once #120 is merged.

**Comment by AungKoKoLin1997** [comment]
> Updated .github/workflows/test.yml to seggregate sales_team_security from crm; the test setup of sales_team_secrity is incompatible with crm which adds a required field alias_id to the crm.team model.

@yostashiro  I knew it is incompatible with crm but I doubt that this is the root case of tests failed because crm_exception runs after sales_team_security installed. Please let me test auditlog together with sales_team_security.

**Comment by AungKoKoLin1997** [comment]
@yostashiro I think I was right. After I put together auditlog with sales_team_security, the tests are failed. I think there is no crm related modules and crm module is not installed in this CI. Then, you can also see the error message. That is not related with required fields alias_id.

**Comment by yostashiro** [comment]
Thanks, Lin. I have reverted your last update and adjusted my comment in `test.yml`.

The incompatibility between `sales_team_security` and `auditlog` has been puzzling me, but let me go ahead and merge this as this has been causing hassles with gitaggregate, and with `sales_team_security` being a new module, it won't affect the production environment.

**Review by yostashiro — APPROVED** [review]

**Pull request merged**
